/*
 * Sample data for the demo. Inserted on first run, only when the database is
 * empty — delete ./data/tracker.db to start over.
 *
 * Every company, person, and note below is fictional.
 *
 * Dates are relative to the day you first run the app, so the dashboard,
 * follow-ups, and charts always look current instead of frozen in the past.
 */

// N days before today; pass a negative number for a future date.
function day(offset) {
  const d = new Date();
  d.setDate(d.getDate() - offset);
  const pad = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate());
}

module.exports = {
  applications: [
    {"company":"Cobalt Systems","role":"Enterprise Customer Success Manager","applied_date":day(52),"priority":"High","location_type":"Remote","salary_range":"$150k-$175k","source":"Referral","interview_landed":true,"status":"Offer Received","recruiter_contact":"Priya Raman","followup_date":null,"notes":"Referred by Priya Raman. Four rounds, ending with an exec conversation. Offer received — negotiating start date.","tags":["CSM"],"job_link":"https://example.com/jobs/cobalt-ecsm"},
    {"company":"Northwind Analytics","role":"Senior Customer Success Manager","applied_date":day(38),"priority":"High","location_type":"Remote","salary_range":"$140k-$165k","source":"Referral","interview_landed":true,"status":"In Progress","recruiter_contact":"Dana Whitfield","followup_date":null,"notes":"Dana passed my resume to the hiring manager. Panel scheduled — prep the retention case study.","tags":["CSM"],"job_link":"https://example.com/jobs/northwind-scsm"},
    {"company":"Lumen Labs","role":"AI Solutions Consultant","applied_date":day(31),"priority":"High","location_type":"Hybrid","salary_range":"$160k-$190k OTE","source":"Company Website","interview_landed":true,"status":"In Progress","recruiter_contact":"Marcus Reyes","followup_date":null,"notes":"Technical exercise today. Review their model-evaluation tooling beforehand.","tags":["AI Strategy"],"job_link":"https://example.com/jobs/lumen-aisc"},
    {"company":"Vireo Data","role":"AI Engagement Manager","applied_date":day(24),"priority":"Medium","location_type":"Remote","salary_range":"$135k-$160k","source":"LinkedIn","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":day(-5),"notes":"Sofia offered to flag my application internally.","tags":["AI Strategy","CSM"],"job_link":null},
    {"company":"Quarry Analytics","role":"Customer Success Manager, Mid-Market","applied_date":day(19),"priority":"Medium","location_type":"Remote","salary_range":"$120k-$140k","source":"Company Website","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":day(0),"notes":"Applied through their careers page. Time to check in.","tags":["CSM"],"job_link":"https://example.com/jobs/quarry-csm"},
    {"company":"Tessellate","role":"Senior Customer Success Manager","applied_date":day(17),"priority":"Medium","location_type":"Remote","salary_range":null,"source":"LinkedIn","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":day(4),"notes":"Follow-up is overdue — send a short nudge.","tags":["CSM"],"job_link":null},
    {"company":"Sandbar Media","role":"Customer Success Manager","applied_date":day(12),"priority":"Low","location_type":"Hybrid","salary_range":"$110k-$125k","source":"Indeed","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["CSM"],"job_link":null},
    {"company":"Fernwood Legal Tech","role":"AI Strategist","applied_date":day(9),"priority":"High","location_type":"Remote","salary_range":"$155k-$180k","source":"Company Website","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":"Strong fit on paper. Messaged the hiring manager after applying.","tags":["AI Strategy"],"job_link":"https://example.com/jobs/fernwood-ais"},
    {"company":"Gridpoint AI","role":"AI Solutions Manager","applied_date":day(6),"priority":"Medium","location_type":"Remote","salary_range":"$145k-$170k","source":"Other","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["AI Strategy"],"job_link":null},
    {"company":"Brightline Education","role":"Customer Success Manager","applied_date":day(5),"priority":"Low","location_type":"On-site","salary_range":"$95k-$115k","source":"Glassdoor","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["CSM"],"job_link":null},
    {"company":"Halcyon Health","role":"Client Success Manager","applied_date":day(3),"priority":"Medium","location_type":"Remote","salary_range":"$125k-$145k","source":"LinkedIn","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["CSM"],"job_link":null},
    {"company":"Trellis Analytics","role":"Customer Success Manager","applied_date":day(2),"priority":"Medium","location_type":"Remote","salary_range":null,"source":"Company Website","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["CSM"],"job_link":null},
    {"company":"Wexford Cloud","role":"Senior Customer Success Manager","applied_date":day(1),"priority":"High","location_type":"Remote","salary_range":"$140k-$160k","source":"Referral","interview_landed":false,"status":"In Progress","recruiter_contact":null,"followup_date":null,"notes":"Jordan suggested reaching out to their VP of CS.","tags":["CSM"],"job_link":null},
    {"company":"Meridian Cloud","role":"Implementation Manager","applied_date":day(74),"priority":"Medium","location_type":"Hybrid","salary_range":"$130k-$150k","source":"Other","interview_landed":true,"status":"Rejected","recruiter_contact":"Tom Gallagher","followup_date":null,"notes":"Two rounds. They went with someone who had more platform-migration experience.","tags":["CSM"],"job_link":null},
    {"company":"Harborview Health","role":"Customer Success Manager","applied_date":day(88),"priority":"Medium","location_type":"On-site","salary_range":"$105k-$120k","source":"Indeed","interview_landed":true,"status":"Rejected","recruiter_contact":null,"followup_date":null,"notes":"Rejected after the recruiter screen — they needed on-site five days a week.","tags":["CSM"],"job_link":null},
    {"company":"Kestrel Security","role":"Enterprise Customer Success Manager","applied_date":day(59),"priority":"High","location_type":"Remote","salary_range":"$145k-$170k","source":"Company Website","interview_landed":true,"status":"Rejected","recruiter_contact":"Nina Alvarez","followup_date":null,"notes":"Made it to the panel. Feedback: wanted deeper security-domain background.","tags":["CSM"],"job_link":null},
    {"company":"Beacon Logistics","role":"Customer Success Manager","applied_date":day(81),"priority":"Low","location_type":"Hybrid","salary_range":null,"source":"LinkedIn","interview_landed":false,"status":"Rejected","recruiter_contact":null,"followup_date":null,"notes":"Role was filled internally.","tags":["CSM"],"job_link":null},
    {"company":"Ridgeway Financial","role":"Client Partner","applied_date":day(70),"priority":"Low","location_type":"Hybrid","salary_range":"$115k-$135k","source":"Other","interview_landed":false,"status":"Rejected","recruiter_contact":null,"followup_date":null,"notes":null,"tags":[],"job_link":null},
    {"company":"Alder & Finch","role":"Client Success Lead","applied_date":day(66),"priority":"Low","location_type":"On-site","salary_range":"$100k-$118k","source":"Referral","interview_landed":true,"status":"Withdrawn","recruiter_contact":null,"followup_date":null,"notes":"Withdrew after the screen — the travel expectation was 60%.","tags":["CSM"],"job_link":null},
    {"company":"Pinecrest Software","role":"Strategic Account Manager","applied_date":day(96),"priority":"Medium","location_type":"Remote","salary_range":null,"source":"LinkedIn","interview_landed":false,"status":"Never Heard Back","recruiter_contact":null,"followup_date":null,"notes":"Easy Apply. Never got a confirmation email.","tags":[],"job_link":null},
    {"company":"Orchid Robotics","role":"AI Adoption Lead","applied_date":day(103),"priority":"Medium","location_type":"Remote","salary_range":"$150k-$180k","source":"Company Website","interview_landed":false,"status":"Never Heard Back","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["AI Strategy"],"job_link":null},
    {"company":"Solstice Commerce","role":"Scaled Customer Success Manager","applied_date":day(110),"priority":"Low","location_type":"Remote","salary_range":"$98k-$115k","source":"Other","interview_landed":false,"status":"Never Heard Back","recruiter_contact":null,"followup_date":null,"notes":null,"tags":["CSM"],"job_link":null}
  ],

  networking: [
    {"name":"Priya Raman","company":"Cobalt Systems","title":"VP, Customer Success","how_connected":"Referral","last_contact_date":day(6),"followup_date":null,"referred_job":true,"job_link":null,"notes":"Championed my application internally. Send a thank-you once the offer is signed.","status":"Active"},
    {"name":"Dana Whitfield","company":"Northwind Analytics","title":"Talent Partner","how_connected":"LinkedIn","last_contact_date":day(11),"followup_date":null,"referred_job":true,"job_link":null,"notes":"Very responsive. Happy to answer questions between rounds.","status":"Active"},
    {"name":"Marcus Reyes","company":"Lumen Labs","title":"Director, Solutions Engineering","how_connected":"Conference","last_contact_date":day(14),"followup_date":null,"referred_job":false,"job_link":null,"notes":"Met at a meetup. Walked me through how their team is structured.","status":"Active"},
    {"name":"Jordan Ellis","company":"Independent","title":"Career Coach","how_connected":"Other","last_contact_date":day(20),"followup_date":day(-3),"referred_job":false,"job_link":null,"notes":"Monthly check-in. Bring the updated pipeline numbers.","status":"Active"},
    {"name":"Sofia Bennett","company":"Vireo Data","title":"Customer Success Manager","how_connected":"LinkedIn","last_contact_date":day(16),"followup_date":day(1),"referred_job":false,"job_link":null,"notes":"Said she would flag my application to her manager. No reply yet.","status":"Awaiting Reply"},
    {"name":"Tom Gallagher","company":"Meridian Cloud","title":"Technical Recruiter","how_connected":"Referral","last_contact_date":day(62),"followup_date":null,"referred_job":false,"job_link":null,"notes":"Suggested staying in touch for future openings on the platform team.","status":"Dormant"},
    {"name":"Alex Cho","company":"Pinecrest Software","title":"Engineering Manager","how_connected":"Alumni Network","last_contact_date":day(84),"followup_date":null,"referred_job":false,"job_link":null,"notes":"Same alma mater. Offered to make an intro if a CS role opens up.","status":"Dormant"},
    {"name":"Nina Alvarez","company":"Kestrel Security","title":"Talent Acquisition Lead","how_connected":"Company Website","last_contact_date":day(48),"followup_date":null,"referred_job":false,"job_link":null,"notes":"Closed the loop after the panel rejection.","status":"Closed"}
  ],

  interviews: [
    {"company":"Cobalt Systems","role":"Enterprise Customer Success Manager","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(46),"interview_time":"10:00","duration_minutes":30,"interviewers":"Ravi Menon","interviewer_titles":"Technical Recruiter","notes":"Covered comp expectations and the interview loop.","outcome":"Passed"},
    {"company":"Cobalt Systems","role":"Enterprise Customer Success Manager","round_number":2,"interview_type":"Hiring Manager","interview_date":day(40),"interview_time":"13:00","duration_minutes":45,"interviewers":"Priya Raman","interviewer_titles":"VP, Customer Success","notes":"Book of business is roughly 20 enterprise accounts.","outcome":"Passed"},
    {"company":"Cobalt Systems","role":"Enterprise Customer Success Manager","round_number":3,"interview_type":"Case Study","interview_date":day(33),"interview_time":"11:00","duration_minutes":60,"interviewers":"Priya Raman; Daniel Okafor","interviewer_titles":"VP, Customer Success; Director, Onboarding","notes":"Presented a 90-day turnaround plan for an at-risk account.","outcome":"Passed"},
    {"company":"Cobalt Systems","role":"Enterprise Customer Success Manager","round_number":4,"interview_type":"Executive","interview_date":day(27),"interview_time":"15:30","duration_minutes":30,"interviewers":"Helen Marsh","interviewer_titles":"Chief Customer Officer","notes":"Mostly values and long-term goals.","outcome":"Passed"},
    {"company":"Northwind Analytics","role":"Senior Customer Success Manager","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(30),"interview_time":"09:30","duration_minutes":30,"interviewers":"Dana Whitfield","interviewer_titles":"Talent Partner","notes":null,"outcome":"Passed"},
    {"company":"Northwind Analytics","role":"Senior Customer Success Manager","round_number":2,"interview_type":"Hiring Manager","interview_date":day(21),"interview_time":"14:00","duration_minutes":45,"interviewers":"Grace Lindqvist","interviewer_titles":"Senior Manager, Customer Success","notes":"Team of eight, mix of mid-market and enterprise.","outcome":"Passed"},
    {"company":"Northwind Analytics","role":"Senior Customer Success Manager","round_number":3,"interview_type":"Panel","interview_date":day(-4),"interview_time":"12:00","duration_minutes":60,"interviewers":"Grace Lindqvist; Omar Haddad; Lily Chen","interviewer_titles":"Senior Manager, CS; Staff CSM; Solutions Architect","notes":"Bring the retention case study.","outcome":null},
    {"company":"Lumen Labs","role":"AI Solutions Consultant","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(25),"interview_time":"11:15","duration_minutes":30,"interviewers":"Marcus Reyes","interviewer_titles":"Director, Solutions Engineering","notes":"Informal intro call.","outcome":"Passed"},
    {"company":"Lumen Labs","role":"AI Solutions Consultant","round_number":2,"interview_type":"Technical","interview_date":day(0),"interview_time":"14:00","duration_minutes":60,"interviewers":"Ines Duarte","interviewer_titles":"Staff Solutions Engineer","notes":"Live exercise on their evaluation tooling.","outcome":null},
    {"company":"Meridian Cloud","role":"Implementation Manager","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(70),"interview_time":null,"duration_minutes":30,"interviewers":"Tom Gallagher","interviewer_titles":"Technical Recruiter","notes":null,"outcome":"Passed"},
    {"company":"Meridian Cloud","role":"Implementation Manager","round_number":2,"interview_type":"Hiring Manager","interview_date":day(63),"interview_time":"16:00","duration_minutes":45,"interviewers":"Claire Whitman","interviewer_titles":"Director, Professional Services","notes":"Wanted more hands-on migration experience.","outcome":"Rejected"},
    {"company":"Kestrel Security","role":"Enterprise Customer Success Manager","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(55),"interview_time":"10:30","duration_minutes":30,"interviewers":"Nina Alvarez","interviewer_titles":"Talent Acquisition Lead","notes":null,"outcome":"Passed"},
    {"company":"Kestrel Security","role":"Enterprise Customer Success Manager","round_number":2,"interview_type":"Panel","interview_date":day(48),"interview_time":"13:30","duration_minutes":60,"interviewers":"Ben Ortiz; Maya Srinivasan","interviewer_titles":"Manager, CS; Security Solutions Lead","notes":"Heavy on threat-detection workflows.","outcome":"Rejected"},
    {"company":"Harborview Health","role":"Customer Success Manager","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(80),"interview_time":null,"duration_minutes":20,"interviewers":"Rachel Dunn","interviewer_titles":"Recruiter","notes":"On-site five days a week was a dealbreaker for them.","outcome":"Rejected"},
    {"company":"Alder & Finch","role":"Client Success Lead","round_number":1,"interview_type":"Recruiter Screening","interview_date":day(60),"interview_time":null,"duration_minutes":30,"interviewers":"Peter Vance","interviewer_titles":"Talent Partner","notes":"Travel expectation came in around 60%.","outcome":"Withdrew"}
  ],

  savedJobs: [
    {"company":"Copperline AI","role":"Customer Success Manager","salary_range":"$130k-$150k","location_type":"Remote","source":"LinkedIn","priority":"High","job_link":"https://example.com/jobs/copperline-csm","notes":"Posting closes at the end of the month — tailor the resume first.","saved_date":day(4)},
    {"company":"Juniper Systems","role":"AI Enablement Consultant","salary_range":"$140k-$165k","location_type":"Hybrid","source":"Company Website","priority":"Medium","job_link":null,"notes":"Ask Jordan whether the commute is realistic.","saved_date":day(9)},
    {"company":"Waypoint Labs","role":"Enterprise Customer Success Manager","salary_range":null,"location_type":"Remote","source":"Other","priority":"Low","job_link":null,"notes":"Interesting product, unclear comp band.","saved_date":day(2)}
  ]
};
